-- 图片类型表
CREATE TABLE CMF_SLIDE_TYPE
(
  TYPE        VARCHAR(255)  NOT NULL PRIMARY KEY,
  NAME        VARCHAR(255)  NOT NULL,
  DESCRIPTION VARCHAR(1000) NULL,
  ENABLED     BIT           NOT NULL
)
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='图片类型表';

-- 图片表
CREATE TABLE CMF_SLIDE
(
  ID          VARCHAR(36)   NOT NULL PRIMARY KEY COMMENT "图片ID",
  TITLE       VARCHAR(255)  NULL,
  TYPE        VARCHAR(255)  NOT NULL,
  URI         VARCHAR(255)  NULL,
  CONTENT     VARCHAR(1000) NULL,
  DESCRIPTION VARCHAR(1000) NULL,
  FILE_ID     VARCHAR(255)  NOT NULL,
  LOCALE      VARCHAR(255)  NOT NULL,
  SHOW_ORDER  INT           NOT NULL
)
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='图片表';

-- 内容类型表
CREATE TABLE CMF_POST_TYPE
(
  TYPE              VARCHAR(255)  NOT NULL PRIMARY KEY,
  NAME              VARCHAR(255)  NOT NULL,
  DESCRIPTION       VARCHAR(1000) NULL,
  ADMIN_PAGE_SUFFIX VARCHAR(255)  NOT NULL,
  VIEW_PAGE_SUFFIX  VARCHAR(255)  NOT NULL,
  ENABLED           BIT           NOT NULL
)
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='内容类型表';

-- 内容表
CREATE TABLE CMF_POST
(
  ID              VARCHAR(36)  NOT NULL PRIMARY KEY,
  TYPE            VARCHAR(255) NOT NULL,
  TITLE           VARCHAR(255) NOT NULL,
  THEME_PIC_AF_ID VARCHAR(36)  NULL,
  AUTHOR_ID       VARCHAR(36)  NOT NULL,
  EXCERPT         VARCHAR(255) NULL,
  CONTENT         LONGTEXT     NULL,
  CREATE_DATE     DATETIME     NOT NULL,
  UPDATE_DATE     DATETIME     NOT NULL,
  EXTRA_DATA      LONGTEXT     NULL,
  LOCALE          VARCHAR(255) NOT NULL,
  SHOW_ORDER      INT          NOT NULL,
  IS_TOP          BIT          NOT NULL,
  APPROVED        BIT          NOT NULL
)
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='内容表';

-- 内容附件表
CREATE TABLE CMF_POST_ATTACH
	(
	  ID           VARCHAR(36)  NOT NULL PRIMARY KEY COMMENT '附件ID',
      FILE_ID      VARCHAR(36)  NOT NULL COMMENT '文件归档ID',
	  FILE_NAME    VARCHAR(255) NOT NULL COMMENT '附件文件名',
	  POST_ID      VARCHAR(36)  NOT NULL COMMENT '所属内容ID',
      SHOW_ORDER   INT          NOT NULL COMMENT '附件显示顺序',
	  CONSTRAINT  FK_CMF_POST_ATTACH_P_ID FOREIGN KEY (POST_ID) REFERENCES CMF_POST (ID)
	)
    ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='内容附件表';
CREATE INDEX FK_CMF_POST_ATTACH_P_ID ON CMF_POST_ATTACH (POST_ID);